version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "semiannually"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
